//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockPenSimWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"1280,696\"")]
        public string WindowSize {
            get {
                return ((string)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"useDecimalComma\": false,\r\n  \"hideZeroRatioWeaponColumns\": true,\r\n  \"hideZer" +
            "oRatioDirectionColumns\": true,\r\n  \"updateDefaultBlockdataOverInternet\": true,\r\n " +
            " \"applyKilledBlockCollisionDamage\": false,\r\n  \"HighlightValues\": {\r\n    \"Block L" +
            "ength\": false,\r\n    \"Block Width\": false,\r\n    \"Block Height\": false,\r\n    \"Leng" +
            "th\": false,\r\n    \"Width\": false,\r\n    \"Height\": false,\r\n    \"Length Block Count\"" +
            ": false,\r\n    \"Width Block Count\": false,\r\n    \"Height Block Count\": false,\r\n   " +
            " \"CPU\": false,\r\n    \"Weight (kg)\": false,\r\n    \"STP Laser Blaster (Front)\": fals" +
            "e,\r\n    \"STP Laser Blaster (Side)\": false,\r\n    \"STP Laser Blaster (Top)\": false" +
            ",\r\n    \"STP Plasma Cannon (Front)\": false,\r\n    \"STP Plasma Cannon (Side)\": fals" +
            "e,\r\n    \"STP Plasma Cannon (Top)\": false,\r\n    \"STP Arc Discharger (Front)\": fal" +
            "se,\r\n    \"STP Arc Discharger (Side)\": false,\r\n    \"STP Arc Discharger (Top)\": fa" +
            "lse,\r\n    \"STP Rail Gun (Front)\": false,\r\n    \"STP Rail Gun (Side)\": false,\r\n   " +
            " \"STP Rail Gun (Top)\": false,\r\n    \"TTP Laser Blaster (Front)\": false,\r\n    \"TTP" +
            " Laser Blaster (Side)\": false,\r\n    \"TTP Laser Blaster (Top)\": false,\r\n    \"TTP " +
            "Plasma Cannon (Front)\": false,\r\n    \"TTP Plasma Cannon (Side)\": false,\r\n    \"TTP" +
            " Plasma Cannon (Top)\": false,\r\n    \"TTP Arc Discharger (Front)\": false,\r\n    \"TT" +
            "P Arc Discharger (Side)\": false,\r\n    \"TTP Arc Discharger (Top)\": false,\r\n    \"T" +
            "TP Rail Gun (Front)\": false,\r\n    \"TTP Rail Gun (Side)\": false,\r\n    \"TTP Rail G" +
            "un (Top)\": false,\r\n    \"Score\": true,\r\n    \"Score / CPU\": true,\r\n    \"Score / We" +
            "ight\": true\r\n  },\r\n  \"RowFilters\": {},\r\n  \"ColumnsSort\": {\r\n    \"Score\": 1\r\n  }," +
            "\r\n  \"Cpu\": {\r\n    \"Min\": 1,\r\n    \"Max\": 100\r\n  },\r\n  \"Weight\": {\r\n    \"Min\": 0,\r" +
            "\n    \"Max\": 6000\r\n  },\r\n  \"Length\": {\r\n    \"Min\": 4,\r\n    \"Max\": 9\r\n  },\r\n  \"Wid" +
            "th\": {\r\n    \"Min\": 9,\r\n    \"Max\": 9\r\n  },\r\n  \"Height\": {\r\n    \"Min\": 9,\r\n    \"Ma" +
            "x\": 9\r\n  },\r\n  \"WeaponSettings\": {\r\n    \"LaserBlaster\": {\r\n      \"WeaponCount\": " +
            "6,\r\n      \"WeaponRatio\": 3,\r\n      \"WeaponFrontRatio\": 3,\r\n      \"WeaponSideRati" +
            "o\": 1,\r\n      \"WeaponTopRatio\": 1\r\n    },\r\n    \"PlasmaCannonMax\": {\r\n      \"Weap" +
            "onCount\": 2,\r\n      \"WeaponRatio\": 3,\r\n      \"WeaponFrontRatio\": 1,\r\n      \"Weap" +
            "onSideRatio\": 1,\r\n      \"WeaponTopRatio\": 2\r\n    },\r\n    \"PlasmaCannon\": {\r\n    " +
            "  \"WeaponCount\": 2,\r\n      \"WeaponRatio\": 3,\r\n      \"WeaponFrontRatio\": 1,\r\n    " +
            "  \"WeaponSideRatio\": 1,\r\n      \"WeaponTopRatio\": 2\r\n    },\r\n    \"PlasmaCannonMin" +
            "\": {\r\n      \"WeaponCount\": 2,\r\n      \"WeaponRatio\": 3,\r\n      \"WeaponFrontRatio\"" +
            ": 1,\r\n      \"WeaponSideRatio\": 1,\r\n      \"WeaponTopRatio\": 2\r\n    },\r\n    \"ArcDi" +
            "scharger\": {\r\n      \"WeaponCount\": 3,\r\n      \"WeaponRatio\": 0,\r\n      \"WeaponFro" +
            "ntRatio\": 1,\r\n      \"WeaponSideRatio\": 1,\r\n      \"WeaponTopRatio\": 0\r\n    },\r\n  " +
            "  \"RailGunMax\": {\r\n      \"WeaponCount\": 1,\r\n      \"WeaponRatio\": 1,\r\n      \"Weap" +
            "onFrontRatio\": 1,\r\n      \"WeaponSideRatio\": 0,\r\n      \"WeaponTopRatio\": 0\r\n    }" +
            ",\r\n    \"RailGun\": {\r\n      \"WeaponCount\": 1,\r\n      \"WeaponRatio\": 1,\r\n      \"We" +
            "aponFrontRatio\": 1,\r\n      \"WeaponSideRatio\": 0,\r\n      \"WeaponTopRatio\": 0\r\n   " +
            " },\r\n    \"RailGunMin\": {\r\n      \"WeaponCount\": 1,\r\n      \"WeaponRatio\": 1,\r\n    " +
            "  \"WeaponFrontRatio\": 1,\r\n      \"WeaponSideRatio\": 0,\r\n      \"WeaponTopRatio\": 0" +
            "\r\n    }\r\n  },\r\n  \"Weapons\": {\r\n    \"LaserBlaster\": {\r\n      \"name\": \"Laser Blast" +
            "er\",\r\n      \"cpu\": 20,\r\n      \"damage\": 24.0,\r\n      \"pellets\": 1.0,\r\n      \"rad" +
            "ius\": 0.0,\r\n      \"splashShape\": 0,\r\n      \"energy\": 2000.0,\r\n      \"cooldown\": " +
            "0.6,\r\n      \"impulse\": 2750\r\n    },\r\n    \"PlasmaCannonMax\": {\r\n      \"name\": \"Pl" +
            "asma Cannon (37.5m)\",\r\n      \"cpu\": 60,\r\n      \"damage\": 600.0,\r\n      \"pellets\"" +
            ": 9.0,\r\n      \"radius\": 25.0,\r\n      \"splashShape\": 1,\r\n      \"energy\": 1000.0,\r" +
            "\n      \"cooldown\": 2.5,\r\n      \"impulse\": 2750\r\n    },\r\n    \"PlasmaCannon\": {\r\n " +
            "     \"name\": \"Plasma Cannon (78.75m)\",\r\n      \"cpu\": 60,\r\n      \"damage\": 340.0," +
            "\r\n      \"pellets\": 9.0,\r\n      \"radius\": 25.0,\r\n      \"splashShape\": 1,\r\n      \"" +
            "energy\": 1000.0,\r\n      \"cooldown\": 2.5,\r\n      \"impulse\": 2750\r\n    },\r\n    \"Pl" +
            "asmaCannonMin\": {\r\n      \"name\": \"Plasma Cannon (120m)\",\r\n      \"cpu\": 60,\r\n    " +
            "  \"damage\": 80.0,\r\n      \"pellets\": 9.0,\r\n      \"radius\": 25.0,\r\n      \"splashSh" +
            "ape\": 1,\r\n      \"energy\": 1000.0,\r\n      \"cooldown\": 2.5,\r\n      \"impulse\": 2750" +
            "\r\n    },\r\n    \"ArcDischarger\": {\r\n      \"name\": \"Arc Discharger\",\r\n      \"cpu\": " +
            "40,\r\n      \"damage\": 15000.0,\r\n      \"pellets\": 11.0,\r\n      \"radius\": 30.0,\r\n  " +
            "    \"splashShape\": 1,\r\n      \"energy\": 120000.0,\r\n      \"cooldown\": 6.0,\r\n      " +
            "\"impulse\": 5000\r\n    },\r\n    \"RailGunMax\": {\r\n      \"name\": \"Rail Gun (70m)\",\r\n " +
            "     \"cpu\": 120,\r\n      \"damage\": 810.0,\r\n      \"pellets\": 12.0,\r\n      \"radius\"" +
            ": 3.0,\r\n      \"splashShape\": 2,\r\n      \"energy\": 4500.0,\r\n      \"cooldown\": 3.5," +
            "\r\n      \"impulse\": 2750\r\n    },\r\n    \"RailGun\": {\r\n      \"name\": \"Rail Gun (47.5" +
            "m)\",\r\n      \"cpu\": 120,\r\n      \"damage\": 480.0,\r\n      \"pellets\": 12.0,\r\n      \"" +
            "radius\": 1.5,\r\n      \"splashShape\": 2,\r\n      \"energy\": 2350.0,\r\n      \"cooldown" +
            "\": 3.5,\r\n      \"impulse\": 2750\r\n    },\r\n    \"RailGunMin\": {\r\n      \"name\": \"Rail" +
            " Gun (25m)\",\r\n      \"cpu\": 120,\r\n      \"damage\": 150.0,\r\n      \"pellets\": 1.0,\r\n" +
            "      \"radius\": 0.0,\r\n      \"splashShape\": 0,\r\n      \"energy\": 200.0,\r\n      \"co" +
            "oldown\": 3.5,\r\n      \"impulse\": 2750\r\n    }\r\n  },\r\n  \"Materials\": {\r\n    \"Airium" +
            "\": {\r\n      \"name\": \"Airium\",\r\n      \"density\": 0.728,\r\n      \"connectionStrengt" +
            "h\": 1.59,\r\n      \"energyAbsorption\": 2500\r\n    },\r\n    \"Moderonium\": {\r\n      \"n" +
            "ame\": \"Moderonium\",\r\n      \"density\": 1.8,\r\n      \"connectionStrength\": 2.65,\r\n " +
            "     \"energyAbsorption\": 5000\r\n    },\r\n    \"Ladium\": {\r\n      \"name\": \"Ladium\",\r" +
            "\n      \"density\": 7.32,\r\n      \"connectionStrength\": 3.35225,\r\n      \"energyAbso" +
            "rption\": 7500\r\n    }\r\n  }\r\n}")]
        public string IndexStore {
            get {
                return ((string)(this["IndexStore"]));
            }
            set {
                this["IndexStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ThemeOverride {
            get {
                return ((string)(this["ThemeOverride"]));
            }
            set {
                this["ThemeOverride"] = value;
            }
        }
    }
}
